### ISSUE TITLE
goapp depolyとgo runで結果が異なる

### ISSUE THREAD

**Issue by worifon** [kyokomi/go-docomo#8]
こんばんわ、はじめまして。
example/dialogue.goをgo-appengineで実行したいのですが、下記のエラーが返ります。
{"requestError": {"polixyException": {"messageId":"POLSLA006","text":"Access denied for request method"}}}
go runの場合は問題ありません。

appengineの場合は追加で必要なコードなどがありますでしょうか？

**Comment by kyokomi** [comment]
@worifon 
appengineの場合はrequestで受け取った `x.net.Context` を使う必要がありまして、[ここ](https://github.com/kyokomi/go-docomo/blob/master/example/dialogue.go#L32)を以下のように呼び出せばうまくいくかと思います！

``` go
res, err := d.Dialogue.WithContext(ctx).Get(zatsu, true)
```

**Comment by worifon** [comment]
うまくいきました。ありがとうございました。
